### ISSUE TITLE
Installing Without Numba Support

### ISSUE THREAD

**Issue by defencedog** [yoelcortes/flexsolve#1]
I am on ARM64 & `numba` is creating problem. Can i use `flexsolve` without numba install ...I mean any compiling flag that I can use

**Comment by yoelcortes** [comment]
@defencedog, a flag is available through numba, you can run the following before importing flexsolve:

```python
import os
os.environ["NUMBA_DISABLE_JIT"] = "1"
```

Out of curiosity, at which point is numba problematic? Can you post the traceback and your vesions of numba and llvmlite here? If it's during imports, I can add a try and exception block to avoid this. I may try checking with numba people to see if this is a known issue later.

Thanks,

**Comment by defencedog** [comment]
@yoelcortes Thanks for replying. I completely build with SUCCESS `numba` with `gcc-11` but discussion goes on & I cannot import it
https://github.com/numba/numba/issues/8584

**Comment by yoelcortes** [comment]
@defencedog, perfect, thanks for sharing. Were you able to run flexsolve with the flag? If it worked for you, I may try adding an try-except block for numba import errors and use this flag.

**Comment by defencedog** [comment]
@yoelcortes No! As aforementioned problem with `numba` isn't solved so `flexsolve` too cannot be imported

**Comment by defencedog** [comment]
@yoelcortes Hey friend problem is resolved. The issue seems to be math library which is provided by Android system itself & is to be included in build command like this @ https://github.com/termux-user-repository/tur/issues/147#issuecomment-1310625296

**Comment by yoelcortes** [comment]
@defencedog, excellent! Glad to know you were able to get it resolved. Thanks again for posting, it will help others resolve such issues too.
